### ISSUE TITLE
Sprint#1 tasks

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage4/grad.then#238]
The list of **Sprint#1** tasks:
 - [ ] User Story: Button in `Hero` #129
 - [ ] Apollo setup for Gatsby #235 
 - [ ] Move app state to `apollo-link-state` #237
 - [ ] Handle environment variables with `dotenv` #223 
 - [ ] setup UI testing #230 
 - [ ] README update #233

**Comment by mar-bi** [comment]
Failed

**Comment by spences10** [comment]
>Failed

What's happened?

**Comment by mar-bi** [comment]
We didn't succeed to accomplish tasks from the list during the sprint (last week). 
They moved to the next sprint.

**Comment by spences10** [comment]
😞
